db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/test
  username: postgres
  password: russel
hibernate:
  dialect: org.hibernate.dialect.PostgreSQL9Dialect
  show_sql: false
  format_sql: true
